-- Auto-generated from schema-map-postgres.yaml (map@sha1:8C4F2BC1C4D22EE71E27B5A7968C71E32D8D884D)
-- engine: postgres
-- table:  rbac_repo_snapshots

CREATE TABLE IF NOT EXISTS rbac_repo_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repo_id BIGINT NOT NULL,
  commit_id VARCHAR(128) NOT NULL,
  taken_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  metadata JSONB NULL,
  CONSTRAINT uq_rbac_repo_snap UNIQUE (repo_id, commit_id)
);
