-- Auto-generated from schema-map-postgres.yaml (map@sha1:FAEA49A5D5F8FAAD9F850D0F430ED451C5C1D707)
-- engine: postgres
-- table:  rbac_repo_snapshots

CREATE TABLE IF NOT EXISTS rbac_repo_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repo_id BIGINT NOT NULL,
  commit_id VARCHAR(128) NOT NULL,
  taken_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  metadata JSONB NULL,
  CONSTRAINT uq_rbac_repo_snap UNIQUE (repo_id, commit_id)
);
